#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Stopping a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="stop" --log_path="/var/log/$app/$app.log"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression --message="Updating NGINX web server configuration..." --weight=1

ynh_change_url_nginx_config

#=================================================
# CHANGE THE URL IN .ENV.LOCAL AND REBUILD THE APP
#=================================================

ynh_script_progression --message="Setting the new URL..." --weight=1

if [ $change_domain -eq 1 ]
then
	ynh_replace_string --match_string="NEXT_PUBLIC_SITE_DOMAIN=$old_domain$old_path" --replace_string="NEXT_PUBLIC_SITE_DOMAIN=$new_domain$new_path" --target_file="$install_dir/.env.local"
fi

if [ $change_path -eq 1 ]
then
	if [ "$old_path" = "/" ]; then
		old_next_path=""
	else
		old_next_path=$old_path
	fi

	if [ "$new_path" = "/" ]; then
		new_next_path=""
		next_path=""
	else
		new_next_path=$new_path
		next_path=$new_path
	fi

	ynh_add_config --template="manifest.json" --destination="$install_dir/public/manifest.json"

	ynh_add_config --template="next.config.js" --destination="$install_dir/next.config.js"

	ynh_replace_string --match_string="src={useColorModeValue(\"$old_next_path/banner_light.svg\", \"$old_next_path/banner_dark.svg\")}" --replace_string="src={useColorModeValue(\"$new_next_path/banner_light.svg\", \"$new_next_path/banner_dark.svg\")}" --target_file="$install_dir/components/Header.tsx"

	ynh_replace_string --match_string="href=\"$old_next_path/favicon" --replace_string="href=\"$new_next_path/favicon" --target_file="$install_dir/components/CustomHead.tsx"

	ynh_replace_string --match_string="href=\"$old_next_path/apple" --replace_string="href=\"$new_next_path/apple" --target_file="$install_dir/components/CustomHead.tsx"

	ynh_replace_string --match_string="href=\"$old_next_path/manifest" --replace_string="href=\"$new_next_path/manifest" --target_file="$install_dir/components/CustomHead.tsx"
fi

chown $app:www-data "$install_dir/public/manifest.json"
chown $app:www-data "$install_dir/next.config.js"
chmod 664 "$install_dir/public/manifest.json"
chmod 664 "$install_dir/next.config.js"

#=================================================
# REBUILDING AND INSTALL THE APP
#=================================================
ynh_script_progression --message="Rebuilding the app..." --weight=1

ynh_use_nodejs
ynh_exec_warn_less yarn --cwd "$install_dir" build

chown -R $app:$app "$install_dir/.next"

#=================================================
# GENERIC FINALISATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Change of URL completed for $app" --last
