#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

ynh_config_change_url_nginx

#=================================================
# CHANGE THE URL IN .ENV.LOCAL AND REBUILD THE APP
#=================================================

ynh_script_progression "Setting the new URL..."

if [ $change_domain -eq 1 ]
then
	ynh_replace --match="NEXT_PUBLIC_SITE_DOMAIN=$old_domain$old_path" --replace="NEXT_PUBLIC_SITE_DOMAIN=$new_domain$new_path" --file="$install_dir/.env.local"
fi

if [ $change_path -eq 1 ]
then
	if [ "$old_path" = "/" ]; then
		old_next_path=""
	else
		old_next_path=$old_path
	fi

	if [ "$new_path" = "/" ]; then
		new_next_path=""
		next_path=""
	else
		new_next_path=$new_path
		next_path=$new_path
	fi

	ynh_config_add --template="manifest.json" --destination="$install_dir/public/manifest.json"

	ynh_config_add --template="next.config.js" --destination="$install_dir/next.config.js"

	ynh_replace --match="src={useColorModeValue(\"$old_next_path/banner_light.svg\", \"$old_next_path/banner_dark.svg\")}" --replace="src={useColorModeValue(\"$new_next_path/banner_light.svg\", \"$new_next_path/banner_dark.svg\")}" --file="$install_dir/components/Header.tsx"

	ynh_replace --match="href=\"$old_next_path/favicon" --replace="href=\"$new_next_path/favicon" --file="$install_dir/components/CustomHead.tsx"

	ynh_replace --match="href=\"$old_next_path/apple" --replace="href=\"$new_next_path/apple" --file="$install_dir/components/CustomHead.tsx"

	ynh_replace --match="href=\"$old_next_path/manifest" --replace="href=\"$new_next_path/manifest" --file="$install_dir/components/CustomHead.tsx"
fi

chown $app:www-data "$install_dir/public/manifest.json"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:www-data "$install_dir/next.config.js"
chmod 664 "$install_dir/public/manifest.json"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 664 "$install_dir/next.config.js"

#=================================================
# REBUILDING AND INSTALL THE APP
#=================================================
ynh_script_progression "Rebuilding the app..."

ynh_hide_warnings yarn --cwd "$install_dir" build

chown -R $app:$app "$install_dir/.next"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
