#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression --message="Setting up source files..." --weight=1

# Download, check integrity, uncompress and patch the source from app.src
ynh_setup_source --dest_dir="$install_dir"

chown -R $app:www-data "$install_dir"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression --message="Adding system configurations related to $app..." --weight=1

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_add_nginx_config

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression --message="Adding a configuration file..." --weight=1

ynh_add_config --template=".env.local" --destination="$install_dir/.env.local"

chmod 400 "$install_dir/.env.local"
chown $app:$app "$install_dir/.env.local"

#=================================================
# CONFIGURATION FOR SUBPATH
#=================================================

ynh_secure_remove --file="$install_dir/public/manifest.json"
ynh_secure_remove --file="$install_dir/next.config.js"

if [ "$path" = "/" ]; then
	next_path=""
else
	next_path=$path
fi

ynh_add_config --template="manifest.json" --destination="$install_dir/public/manifest.json"

ynh_add_config --template="next.config.js" --destination="$install_dir/next.config.js"

ynh_replace_string --match_string="src={useColorModeValue(\"/banner_light.svg\", \"/banner_dark.svg\")}" --replace_string="src={useColorModeValue(\"$next_path/banner_light.svg\", \"$next_path/banner_dark.svg\")}" --target_file="$install_dir/components/Header.tsx"

ynh_replace_string --match_string="href=\"/favicon" --replace_string="href=\"$next_path/favicon" --target_file="$install_dir/components/CustomHead.tsx"

ynh_replace_string --match_string="href=\"/apple" --replace_string="href=\"$next_path/apple" --target_file="$install_dir/components/CustomHead.tsx"

ynh_replace_string --match_string="href=\"/manifest" --replace_string="href=\"$next_path/manifest" --target_file="$install_dir/components/CustomHead.tsx"

chown $app:www-data "$install_dir/public/manifest.json"
chown $app:www-data "$install_dir/next.config.js"
chmod 664 "$install_dir/public/manifest.json"
chmod 664 "$install_dir/next.config.js"

#=================================================
# BUILD AND INSTALL THE APP
#=================================================
ynh_script_progression --message="Building the app..." --weight=1

ynh_install_nodejs --nodejs_version=$nodejs_version
ynh_use_nodejs
yarn config set enableTelemetry 0
ynh_exec_warn_less yarn --cwd "$install_dir" install
yarn --cwd "$install_dir" run next telemetry disable
ynh_exec_warn_less yarn --cwd "$install_dir" build

chown -R $app:$app "$install_dir/node_modules"
chown -R $app:$app "$install_dir/.next"

#=================================================
# GENERIC FINALIZATION
#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression --message="Starting a systemd service..." --weight=1

ynh_add_systemd_config

yunohost service add $app --description="alternative to google translate" --log="/var/log/$app/$app.log"

# Start a systemd service
ynh_systemd_action --service_name=$app --action="start" --log_path="/var/log/$app/$app.log"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Installation of $app completed" --last
